'use strict';
const assert=require('assert'); const crypto=require('crypto'); const {VerifiedUpdateInstallCoordinator}=require('../src/verified-update-install-coordinator');
(async()=>{
 const artifactSha256=crypto.createHash('sha256').update('payload').digest('hex'); const payloadManifestSha256=crypto.createHash('sha256').update('manifest').digest('hex'); const calls=[];
 const updater={verifySignedManifest(m,s){calls.push(['verify',m.version,s]);return{verified:true,payloadSha256:payloadManifestSha256}},async downloadArtifact(m,{resume}){calls.push(['download',m.version,resume]);return{path:'/tmp/download.bin',sha256:artifactSha256,size:7}},async stageArtifact(m,p){calls.push(['stage',m.version,p]);return'/tmp/staged.exe'}};
 const installer={async install(i){calls.push(['install',i.version,i.payloadPath,i.expectedSha256]);return{current:'C:\\LLera\\app\\LLera.exe',version:i.version,sha256:i.expectedSha256,verified:true}}};
 let safeMode=false, stableMarks=0; const watchdog={async launchProfile(){return safeMode?{mode:'safe'}:{mode:'normal'}},async markStable(){stableMarks+=1}};
 const c=new VerifiedUpdateInstallCoordinator({updater,installer,watchdog,now:()=> '2026-08-30T08:00:00+03:00'});
 const manifest={version:'5.4.0-reconstructed.1',artifact:{sha256:artifactSha256,size:7,url:'https://example.invalid/LLera.exe'}};
 const ok=await c.apply({manifest,signatureBase64:'signed-manifest',resume:true,selfTestTimeoutMs:9000});
 assert.strictEqual(ok.ok,true); assert.strictEqual(ok.verified,true); assert.strictEqual(ok.artifactSha256,artifactSha256); assert.strictEqual(ok.manifestPayloadSha256,payloadManifestSha256); assert.strictEqual(stableMarks,1); assert.deepStrictEqual(calls.map(x=>x[0]),['verify','download','stage','install']);
 safeMode=true; const before=calls.length; const blocked=await c.apply({manifest,signatureBase64:'signed-manifest'}); assert.strictEqual(blocked.blocked,true); assert.strictEqual(blocked.reason,'watchdog_safe_mode'); assert.strictEqual(calls.length,before+1);
 safeMode=false; const failing=new VerifiedUpdateInstallCoordinator({updater,installer:{async install(){throw new Error('installed-app self-test failed; rollback completed')}},watchdog}); const rb=await failing.apply({manifest,signatureBase64:'signed-manifest'}); assert.strictEqual(rb.ok,false); assert.strictEqual(rb.rolledBack,true);
 let digestBlocked=false; const bad=new VerifiedUpdateInstallCoordinator({updater:{...updater,async downloadArtifact(){return{path:'/tmp/bad.bin',sha256:'0'.repeat(64),size:7}}},installer,watchdog}); try{await bad.apply({manifest,signatureBase64:'signed-manifest'})}catch(e){digestBlocked=/digest diverges/.test(e.message)} assert.strictEqual(digestBlocked,true);
 const unstableWatchdog={async launchProfile(){return{mode:'normal'}},async markStable(){throw new Error('simulated durable watchdog state failure')}};
 const unstable=new VerifiedUpdateInstallCoordinator({updater,installer,watchdog:unstableWatchdog,now:()=> '2026-08-30T08:01:00+03:00'});
 const stability=await unstable.apply({manifest,signatureBase64:'signed-manifest'});
 assert.strictEqual(stability.ok,false); assert.strictEqual(stability.blocked,true); assert.strictEqual(stability.phase,'watchdog-stability-commit'); assert.strictEqual(stability.reason,'watchdog_stability_commit_failed'); assert.strictEqual(stability.installedVerified,true); assert.strictEqual(stability.artifactSha256,artifactSha256); assert.strictEqual(stability.manifestPayloadSha256,payloadManifestSha256); assert.strictEqual(unstable.status().latest.phase,'watchdog-stability-commit');
 console.log('verified update/install bridge PASS',{signedManifestGate:true,digestContinuity:true,windowsSelfTestGate:true,rollbackSurfaced:true,watchdogSafeModeGate:true,watchdogStabilityCommitFailClosed:true});
})().catch(e=>{console.error(e);process.exit(1)});
