'use strict';
const $=id=>document.getElementById(id);let state=null,attached=[];
const text=x=>String(x==null?'':x);const announce=x=>$('live').textContent=x;
function el(tag,attrs={},content=''){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?n.className=v:k.startsWith('on')?n.addEventListener(k.slice(2),v):n.setAttribute(k,v));if(content)n.textContent=content;return n}
function render(){const active=state.activeConversation;$('title').textContent=active?.title||'New conversation';$('runtime').textContent=state.notice||`${state.runtime.state}${state.runtime.model?` · ${state.runtime.model}`:''}`;$('model').textContent=state.models.length?`${state.models.length} local model${state.models.length>1?'s':''}`:'No model';$('send').disabled=false;const chats=$('chats');chats.replaceChildren(...state.conversations.map(c=>{const b=el('button',{class:`chat ${c.id===active?.id?'active':''}`,onclick:async()=>{state=await window.llera.selectConversation(c.id);render()}},c.title);b.append(el('small',{},c.preview));return b}));const root=$('content');root.replaceChildren();if(!active||!active.messages.length){const w=el('div',{class:'welcome'});w.append(el('h1',{},'What would you like to work on?'),el('p',{},'LLera keeps your local work, missions, evidence, and runtime posture together in one desktop workspace.'));const s=el('div',{class:'suggestions'});['Plan a focused task','Create a work mission','Explain a local file'].forEach(x=>s.append(el('button',{onclick:()=>{$('composer').value=x;$('composer').focus()}},x)));w.append(s);root.append(w)}else active.messages.forEach(m=>{const a=el('article',{class:`message ${m.role} ${m.status||''}`});a.append(el('div',{class:'role'},m.role==='user'?'You':'LLera system'),el('div',{class:'bubble'},m.content));if(m.attachments?.length)a.append(el('small',{class:'notice'},m.attachments.map(x=>x.name).join(', ')));root.append(a)});root.scrollTop=root.scrollHeight;renderAttachments()}
function renderAttachments(){$('attachments').replaceChildren(...attached.map(a=>el('span',{class:'attachment'},`${a.name} · ${Math.ceil(a.bytes/1024)} KB`)))}
function drawer(kind){const d=$('drawer');d.classList.add('open');d.replaceChildren(el('button',{class:'icon',onclick:()=>d.classList.remove('open')},'Close'));if(kind==='activity'){d.append(el('h2',{},'Activity'));state.activity.forEach(a=>{const x=el('div',{class:'activity'});x.append(el('strong',{},a.summary),el('small',{},new Date(a.at).toLocaleString()));d.append(x)})}else if(kind==='missions'){d.append(el('h2',{},'Missions'),el('p',{class:'notice'},'Missions keep execution and evidence boundaries explicit.'));d.append(el('button',{class:'new',onclick:async()=>{const goal=prompt('Mission goal');if(goal){state=await window.llera.createMission({title:goal,goal});drawer('missions');render()}}},'Create mission'),...state.missions.map(m=>el('div',{class:'activity'},`${m.title} · ${m.status}`)))}else d.append(el('h2',{},'System & models'),el('p',{class:'notice'},state.notice||`Runtime: ${state.runtime.state}`),el('p',{class:'notice'},'Model execution remains loopback-only; renderer access is isolated.'))}
async function send(){const content=$('composer').value,ids=attached.map(x=>x.id);if(!content.trim()&&!ids.length)return;$('send').disabled=true;try{const out=await window.llera.sendMessage({content,attachmentIds:ids});state=out.snapshot;$('composer').value='';attached=[];render();announce(out.blocked?'Response blocked safely':'Message sent')}catch(e){announce(`Could not send: ${text(e.message||e)}`);$('send').disabled=false}}
function palette(open){$('palette').classList.toggle('open',open);if(open){$('palette-input').value='';$('palette-input').focus();renderCommands('')}}function renderCommands(q){const cmds=[['New conversation',async()=>{state=await window.llera.newConversation();render()}],['Open activity',()=>drawer('activity')],['Open missions',()=>drawer('missions')],['Open system',()=>drawer('system')]];$('commands').replaceChildren(...cmds.filter(([x])=>x.toLowerCase().includes(q.toLowerCase())).map(([x,run])=>el('button',{class:'command',onclick:async()=>{palette(false);await run()}},x)))}
$('new').onclick=async()=>{state=await window.llera.newConversation();render();$('composer').focus()};$('send').onclick=send;$('composer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const bytes=new Uint8Array(await f.arrayBuffer());attached.push(await window.llera.attach({name:f.name,type:f.type,bytes}));renderAttachments()}catch(err){announce(`Attachment rejected: ${text(err.message||err)}`)}e.target.value=''};document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>drawer(b.dataset.drawer));$('palette-open').onclick=()=>palette(true);$('palette-input').oninput=e=>renderCommands(e.target.value);window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();palette(true)}if(e.key==='Escape'){$('drawer').classList.remove('open');palette(false)}});window.llera.productSnapshot().then(x=>{state=x;render()}).catch(e=>announce(`Boot error: ${text(e.message||e)}`));
